### ISSUE TITLE
建议2.0做出pjsk ！！！

### ISSUE THREAD

**Issue by Jekyll-Y** [LordLaffey/MuseDashLightPlay#2]
快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做快做

**Comment by dwdyy** [comment]
@Jekyll-Y fuck you

**Comment by dwdyy** [comment]
@Jekyll-Y wdnmd

**Comment by Ptilopsisw** [comment]
Have got your suggestions.
